# Generated by Django 3.0.8 on 2020-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='valid',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='solution',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Validated')], default=0),
        ),
    ]
