# Generated by Django 3.1 on 2020-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='memory_limit',
            field=models.IntegerField(blank=True, default=52428800, null=True),
        ),
    ]
