# Generated by Django 3.0.8 on 2020-08-06 17:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0002_add_solution_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
