# Generated by Django 3.0.8 on 2020-08-06 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0003_solution_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='text',
        ),
    ]
