# Generated by Django 3.1 on 2020-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20201024_1246'),
        ('judge', '0002_auto_20201025_1303'),
    ]

    operations = [
    ]
