# Generated by Django 3.1 on 2020-08-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0004_remove_solution_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='state',
            field=models.IntegerField(
                choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Validated'), (3, 'Compilation Failed'),
                         (4, 'Crashed')], default=0),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
    ]
