# Generated by Django 3.1 on 2020-08-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0004_remove_solution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
