# Generated by Django 3.1 on 2020-11-08 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_merge_20201025_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('view_grades', 'Can view grades'),)},
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.IntegerField(choices=[(0, 'C++'), (1, 'Python')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='memory_limit',
            field=models.IntegerField(blank=True, default=52428800),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time_limit',
            field=models.FloatField(blank=True, default=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
