# Generated by Django 3.1 on 2020-09-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20200820_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='judge.problem'),
        ),
    ]
