# Generated by Django 3.1 on 2020-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20200910_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.BinaryField(),
        ),
    ]
