# Generated by Django 3.1 on 2020-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20200910_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(),
        ),
    ]
