# Generated by Django 3.1 on 2020-09-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20200910_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField()),
                ('stderr', models.TextField()),
                ('return_code', models.IntegerField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='judge.solution')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.testcase')),
            ],
        ),
    ]
