# Generated by Django 3.1 on 2020-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_testrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='valid',
        ),
        migrations.AddField(
            model_name='testrun',
            name='state',
            field=models.IntegerField(choices=[(0, 'Valid'), (1, 'Crashed'), (2, 'Invalid'), (3, 'Timed Out')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='state',
            field=models.IntegerField(choices=[(0, 'Compilation Pending'), (1, 'Compilation In Progress'), (2, 'Compilation Successful'), (3, 'Compilation Failed')], default=0),
        ),
    ]
