# Generated by Django 3.1 on 2020-09-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20200924_0957'),
        ('judge', '0006_user_solutions'),
    ]

    operations = [
    ]
